apiVersion: v1
kind: ConfigMap
metadata:
  name: store-inventory
  namespace: gamestore
  annotations:
    marketplace.com/comments: "What about janet?"
    # Uncomment to ignore object mutations https://cloud.google.com/kubernetes-engine/docs/add-on/config-sync/how-to/multi-repo#ignoring
    # client.lifecycle.config.k8s.io/mutation: ignore
data:
  single_player: "20"
  cooperative: "60"
  competitive: "300"
