apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: anvils.acme.com
spec:
  group: acme.com
  versions:
    - name: v1
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
              - lbs
              properties:
                lbs:
                  type: integer
                  minimum: 1
                  maximum: 9000
    - name: v2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
              - lbs
              properties:
                lbs:
                  type: integer
                  minimum: 1
                  maximum: 9000
  scope: Namespaced
  names:
    plural: anvils
    singular: anvil
    kind: Anvil