kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gamestore-admin
  namespace: gamestore
subjects:
- kind: ServiceAccount
  name: ns-reconciler-gamestore
  namespace: config-management-system
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io